// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB57P8tE0H5KNjeeeOWbeWr5PU5FVNO8cc',
    appId: '1:563269774596:web:6b88721f74f69be24d3451',
    messagingSenderId: '563269774596',
    projectId: 'youtube-clone-ghassan',
    authDomain: 'clone-ghassan.firebaseapp.com',
    storageBucket: 'youtube-clone-ghassan.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuXeRbuGHZoVbR6YUT85tHg4jz3x_Gkw4',
    appId: '1:563269774596:android:1d1d1fbbc13ba0234d3451',
    messagingSenderId: '563269774596',
    projectId: 'youtube-clone-ghassan',
    storageBucket: 'youtube-clone-ghassan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXfiIVKjI4RWwvw6v1Z2ZRQ1SpZqhJ-6o',
    appId: '1:563269774596:ios:df94d21702cb8d964d3451',
    messagingSenderId: '563269774596',
    projectId: 'youtube-clone-ghassan',
    storageBucket: 'youtube-clone-ghassan.appspot.com',
    iosBundleId: 'com.example.youtubeClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXfiIVKjI4RWwvw6v1Z2ZRQ1SpZqhJ-6o',
    appId: '1:563269774596:ios:df94d21702cb8d964d3451',
    messagingSenderId: '563269774596',
    projectId: 'youtube-clone-ghassan',
    storageBucket: 'youtube-clone-ghassan.appspot.com',
    iosBundleId: 'com.example.youtubeClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB57P8tE0H5KNjeeeOWbeWr5PU5FVNO8cc',
    appId: '1:563269774596:web:f4799dcbfa6a98ae4d3451',
    messagingSenderId: '563269774596',
    projectId: 'youtube-clone-ghassan',
    authDomain: 'clone-ghassan.firebaseapp.com',
    storageBucket: 'youtube-clone-ghassan.appspot.com',
  );
}
